# Generated by Django 3.1.1 on 2020-09-24 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shareds', '0001_initial'),
        ('telephone_operator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(default='', max_length=140)),
                ('destination_number', models.CharField(default=False, max_length=9)),
                ('shipping_time', models.DateTimeField(auto_now_add=True)),
                ('blocked', models.BooleanField(blank=True, default=False, null=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message', to='telephone_operator.telephoneoperator')),
                ('stat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='message', to='shareds.stat')),
            ],
        ),
    ]
