# Generated by Django 3.1.1 on 2020-09-26 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_auto_20200926_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='shipping_time',
            field=models.CharField(default='', max_length=8),
        ),
    ]
