# Generated by Django 3.1.1 on 2020-09-26 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_auto_20200926_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='blocked',
        ),
    ]
