# Generated by Django 3.1.1 on 2020-09-26 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0004_remove_message_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='idmensagem',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
