# Generated by Django 3.1.1 on 2020-09-24 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=60)),
                ('name_pt', models.CharField(default='', max_length=60)),
                ('sigla', models.CharField(blank=True, default='', max_length=4)),
                ('bacen', models.CharField(blank=True, default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=75)),
                ('uf', models.CharField(default='', max_length=2)),
                ('ibge', models.CharField(blank=True, default='', max_length=7)),
                ('ddd', models.CharField(blank=True, default='', max_length=50)),
                ('pais', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shareds', to='shareds.country')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=120)),
                ('ibge', models.CharField(blank=True, default='', max_length=7)),
                ('uf', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shareds', to='shareds.stat')),
            ],
        ),
    ]
