# Generated by Django 3.1.1 on 2020-09-25 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareds', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stat',
            name='pais',
        ),
        migrations.AlterField(
            model_name='city',
            name='uf',
            field=models.CharField(default='', max_length=2),
        ),
    ]
