# Generated by Django 3.1.1 on 2020-09-25 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='broker',
            name='user',
        ),
        migrations.AddField(
            model_name='broker',
            name='name',
            field=models.CharField(default='', max_length=75),
        ),
    ]
